title: ecosynergypartners.com # your name (ecosynergypartners.com) here
logo: "/images/NickHeadShot.jpg" # your photo (or logo) here
description: |
  **I am a tech head and an Entrepreneur.**  
  **Mission Statement:**  
  Eco Synergy Partners is dedicated to reducing plastic and Styrofoam pollution by promoting sustainable alternatives, educating the public, and advocating for systemic change.  
  We empower individuals, businesses, and governments to take meaningful steps toward a cleaner, more sustainable future.  
  We will engage communities through cleanups, events, and auctions that inspire action and raise funds. Offer Eco-friendly merchandise like reusable bottles and bags to reduce waste, fund programs, and promote sustainable living for a cleaner, greener future.  
  [View My LinkedIn Profile](https://www.linkedin.com/in/nick-veech-35870310/)

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Customize theme colors and fonts
defaults:
  - scope:
      path: ""
    values:
      color: "#4CAF50"  # Green color for text and links
      text_color: "#333"  # Default text color
      background_color: "#F5F5F5"  # Light background color

# Add a custom font
plugins:
  - jekyll-fontawesome
