title: ecosynergypartners.com # your name (ecosynergypartners.com) here
logo: "/images/NickHeadShot.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a tech head and an Entrepreneur
  <br><br>
  Mission Statement:
 Eco Synergy Partners is dedicated to reducing plastic and Styrofoam pollution by promoting sustainable alternatives, educating the public, and advocating for systemic change. 
 
 <br><br>We empower individuals, businesses, and governments to take meaningful steps toward a cleaner, more sustainable future.
We will engage communities through cleanups, events, and auctions that inspire action and raise funds. Offer Eco-friendly merchandise like reusable bottles and bags to reduce waste, fund programs, and promote sustainable living for a cleaner, greener future.
 
  <br><br>
  <a href="https://www.linkedin.com/in/nick-veech-35870310/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
